# encoding: utf-8

source 'https://rubygems.org'

gem 'cucumber', '3.1.0'
gem 'capybara', '2.16.1'
gem 'rspec', '3.7.0'
gem 'selenium-webdriver', '3.8.0'
gem 'syntax', '1.2.2'
gem 'rspec-expectations', '3.7.0'
gem 'awesome_print', '1.8.0'
