# encoding: utf-8

source 'https://rubygems.org'

gem 'cucumber', '2.4.0'
gem 'capybara', '2.14.0'
gem 'rspec', '3.6.0'
gem 'selenium-webdriver', '3.4.0'
gem 'syntax', '1.2.1'
gem 'rspec-expectations', '3.6.0'
gem 'awesome_print', '1.7.0'
